# monitoring/prometheus.yml
# Prometheus configuration for monitoring the ingestion service

global:
  scrape_interval: 15s # Scrape metrics every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds
  external_labels:
    cluster: 'ingestion-pipeline'
    environment: 'production'

# Scrape configurations
scrape_configs:
  # Ingestion Service metrics
  - job_name: 'ingestion-service'
    static_configs:
      - targets: ['ingestion-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alerting rules (optional - can be expanded)
rule_files:
  # - 'alerts/*.yml'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']