# config/settings.yaml

general:
  log_level: INFO
  gpu_enabled: False # Set to True if a GPU is available and you want to use it with spaCy

ingestion_service:
  port: 8000
  model_name: "en_core_web_trf" # The spaCy model to use for NER. Change if needed.
  model_cache_dir: "/app/.cache/spacy" # Path for spaCy to cache models.
  dateparser_languages: ["en"] # Languages for dateparser to consider.
  batch_processing_threads: 2 # Number of threads for CLI batch processing. Adjust for CPU cores.

logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    json:
      class: pythonjsonlogger.jsonlogger.JsonFormatter
      format: "%(levelname)s %(asctime)s %(filename)s %(funcName)s %(lineno)d %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: json
      stream: ext://sys.stdout
    ingestion_file:
      class: logging.handlers.RotatingFileHandler
      formatter: json
      filename: /app/logs/ingestion_service.jsonl
      maxBytes: 10485760 # 10 MB
      backupCount: 5
  root:
    handlers: [console]
    level: INFO
  loggers:
    ingestion_service:
      handlers: [ingestion_file, console]
      level: INFO
      propagate: False

# # config/settings.yaml
